services:
  - type: worker
    name: vpo-legal-bot
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
